server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: ${PORT}
  requestLog:
    appenders:
      - type: json-console-access

login: "${BASIC_AUTH_USER}"
password: "${BASIC_AUTH_PASSWORD}"

logging:
  level: INFO
  appenders:
    - type: json-console

spireClientUserName: "${SPIRE_CLIENT_USERNAME}"
spireClientPassword: "${SPIRE_CLIENT_PASSWORD}"
spireClientUrl: "${SPIRE_CLIENT_URL}"

jwtSharedSecret: "${JWT_SHARED_SECRET}"

redis:
  host: "${REDIS_HOST}"
  password: "${REDIS_PASSWORD}"
  port: "${REDIS_PORT}"
  timeout: "${REDIS_TIMEOUT}"
  database: 0
  ssl: "${REDIS_SSL}"
  poolMinIdle: "${REDIS_POOL_MIN_IDLE}"
  poolMaxTotal: "${REDIS_POOL_MAX_TOTAL}"
  keyPrefix: "${REDIS_KEY_PREFIX}"
  key: "${REDIS_KEY}"
  ttl:
    getCustomersByPostcode: "${REDIS_TTL_GET_CUSTOMERS_BY_POSTCODE}"
    getCustomersByEoriNumber: "${REDIS_TTL_GET_CUSTOMERS_BY_EORI_NUMBER}"
    getCustomersByUserId: "${REDIS_TTL_GET_CUSTOMERS_BY_USER_ID}"
    getCustomerById: "${REDIS_TTL_GET_CUSTOMERS_BY_ID}"
    getCustomersByCompanyNumber: "${REDIS_TTL_GET_CUSTOMERS_BY_COMPANY_NUMBER}"
    getCustomersByName: "${REDIS_TTL_GET_CUSTOMERS_BY_NAME}"
    getSite: "${REDIS_TTL_GET_SITE}"
    getSitesByUserId: "${REDIS_TTL_GET_SITES_BY_USER_ID}"
    getSitesByCustomerId: "${REDIS_TTL_GET_SITES_BY_CUSTOMER_ID}"
    getCustomerAdminUsers: "${REDIS_TTL_GET_CUSTOMER_ADMIN_USERS}"
