server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: ${PORT}
  requestLog:
    appenders:
      - type: json-console-access

adminLogin: "${ADMIN_LOGIN}"
adminPassword: "${ADMIN_PASSWORD}"

serviceLogin: "${SERVICE_LOGIN}"
servicePassword: "${SERVICE_PASSWORD}"

logging:
  level: INFO
  appenders:
    - type: json-console

spireClientUserName: "${SPIRE_CLIENT_USERNAME}"
spireClientPassword: "${SPIRE_CLIENT_PASSWORD}"
spireClientUrl: "${SPIRE_CLIENT_URL}"

jwtSharedSecret: "${JWT_SHARED_SECRET}"
