server:
  type: default
  applicationConnectors:
    - type: http
      port: ${PORT}
  adminConnectors:
    - type: http
      port: 8081
  requestLog:
    appenders:
      - type: json-console-access

logging:
  level: INFO
  appenders:
    - type: json-console

spireClientUserName: "${SPIRE_CLIENT_USERNAME}"
spireClientPassword: "${SPIRE_CLIENT_PASSWORD}"
spireClientUrl: "${SPIRE_CLIENT_URL}"

jwtSharedSecret: "${JWT_SHARED_SECRET}"
