server:
  type: default
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

      # Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  appenders:
    - type: console
      includeCallerData : true
      # logFormat: "[%mdc{corrID}] %d [%p] %marker %logger %m%n"
      logFormat: '[%mdc{corrID}] [%d{HH:mm:ss.SSS}] [%-5level] [%class{0}:%method:%line] %msg %n'
      target: stderr
  loggers:
    uk.gov.bis.lite.common.spire.client: TRACE

spireClientUserName: spire-user
spireClientPassword: spire-password
spireClientUrl: https://www.spiretest.trade.gov.uk/spireuat/fox/ispire/
