login: ENTER_USERNAME_HERE
password: ENTER_PASSWORD_HERE

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

      # Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  appenders:
    - type: console
      includeCallerData : true
      # logFormat: "[%mdc{corrID}] %d [%p] %marker %logger %m%n"
      logFormat: '[%mdc{corrID}] [%d{HH:mm:ss.SSS}] [%-5level] [%class{0}:%method:%line] %msg %n'
      target: stderr
  loggers:
    uk.gov.bis.lite.common.spire.client: TRACE

spireClientUserName: ENTER_USERNAME_HERE
spireClientPassword: ENTER_PASSWORD_HERE
spireClientUrl: https://lite-service-mocking-dev.cloudapps.digital/spire/fox/ispire/

jwtSharedSecret: demo-secret-which-is-very-long-so-as-to-hit-the-byte-requirement