server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

login: "ENTER_USERNAME_HERE"
password: "ENTER_PASSWORD_HERE"

logging:
  level: INFO

  appenders:
    - type: console
      includeCallerData : true
      logFormat: '[%mdc{corrID}] [%d{HH:mm:ss.SSS}] [%-5level] [%class{0}:%method:%line] %msg %n'
      target: stderr
  loggers:
    uk.gov.bis.lite.common.spire.client: TRACE

spireClientUserName: "ENTER_USERNAME_HERE"
spireClientPassword: "ENTER_PASSWORD_HERE"
spireClientUrl: "https://lite-service-mocking-dev.cloudapps.digital/spire/fox/ispire/"

jwtSharedSecret: "demo-secret-which-is-very-long-so-as-to-hit-the-byte-requirement"

redis:
  host: localhost
  password: ""
  port: 6379
  timeout: 2000
  database: 0
  ssl: false
  poolMinIdle: 1
  poolMaxTotal: 5
  keyPrefix: local
  key: "lite-customer-service"
  ttl:
    getCustomersByUserId: "2 minutes"
    getCustomerById: "2 minutes"
    getSite: "2 minutes"
    getSitesByUserId: "2 minutes"
    getSitesByCustomerId: "2 minutes"
